---
- name: Depoloy vrf
  gather_facts: no
  hosts: router
  collections: 
    - cisco.nxos    
  tasks:
    - name: Create vrf
      include: "./tasks/vrf.yml"
    #- name: Create route-map
    #  include: "./tasks/route-map.yml"
...
