---
- name: Depoloy vrf
  gather_facts: no
  hosts: router
  collections: 
    - cisco.nxos    
  tasks:
    - name: Create vrf
      include: "./tasks/vrf.yml"
    - name: Create bgp
      include: "./tasks/bgp.yml"
...
