---
- name: Configuration of SW1
  gather_facts: no
  hosts: SW1
  tasks:
    - name: Add vars
      include_vars:
        file: "{{ Survey_Grpcl }}/SW1.yml"
    - name: SW1 Config 
      include: "./tasks/grpcl_worker.yml"
      
- name: Configuration of SW2
  gather_facts: no
  hosts: SW2
  tasks:
    - name: Add vars
      include_vars:
        file: "{{ Survey_Grpcl }}/SW2.yml"
    - name: SW2 Config 
      include: "./tasks/grpcl_worker.yml"
...
