   
---
- name: Add static Route
  collections: 
    - cisco.ios  
  gather_facts: yes
  hosts: ios_router
  tasks:
    - name: Create Interface
      include: "./tasks/int_ios.yml"
    #- name: Config of static routes
    #  include: "./tasks/static_ios.yml"      
...
