---
- name: Remove L3 Interface on all Routers
  gather_facts: no
  hosts: nxos_router
  tasks:
    - nxos_config:
        lines:
        - no interface Vlan{{ vlan_id }}
    
- name: Remove Vlans
  gather_facts: no
  hosts: nxos
  tasks:
    - name: R2 Config (incl. L3 Interface)
      include: "./tasks/sb_l2_remove.yml"
...
