---
- name: Create BGP session incl. redistribution of connected and static
  nxos_bgp_address_family:
    config:
      as_number: 65400
      address_family:
        - afi: ipv4
          safi: unicast
          vrf: '{{ survey_vrf }}'
          default_information:
            originate: "{{ survey_default_orig }}"
          redistribute:
            - protocol: direct
              route_map: RMAP_{{ survey_vrf }}_CONNECTED
            - protocol: static
              route_map: RMAP_{{ survey_vrf }}_STATIC
  when: survey_redist_static|bool

- name: Create BGP session incl. redistribution of connected only
  nxos_bgp_address_family:
    config:
      as_number: 65400
      address_family:
        - afi: ipv4
          safi: unicast
          vrf: '{{ survey_vrf }}'
          default_information:
            originate: "{{ survey_default_orig }}"
          redistribute:
            - protocol: direct
              route_map: RMAP_{{ survey_vrf }}_CONNECTED
  when: not survey_redist_static|bool
...
