--- 
- nxos_config:
    lines:
    - switchport trunk allowed vlan {{ Survey_Action }} {{ Survey_VlanId }}
    parents: interface {{ item.int }}
  with_items: "{{ sw }}"

- name: Gather Facts
  nxos_facts:
    gather_subset:
    - interfaces
  register: output

# Print facts on screen #          
- debug: 
    msg: "{{ ansible_facts }}"

- debug: 
    msg: "{{ ansible_facts['net_interfaces'] }}"

- debug: 
    var: ansible_facts.keys()

- debug: 
    var: output

- name: Display Interfaces
  debug:
    var: item.value.description
  #when: item.value.description is search("grpcl_1")
  with_dict:
   - "{{ ansible_net_interfaces }}"
  ignore_errors: yes   

...
