--- 
- nxos_config:
    lines:
    - switchport trunk allowed vlan {{ Survey_Action }} {{ Survey_VlanId }}
    parents: interface {{ item.int }}
  with_items: "{{ sw }}"

- name: Gather Facts
  nxos_facts:
    gather_subset:
    - interfaces
  register: output

- debug: var=output

- name: Display Interfaces
  debug:
    msg: "{{ description }}"
  when: {{ description }} is {{ Survey_Grpcl }}
  #with_dict:
  # - "{{ ansible_net_interfaces }}"
...
