--- 
- name: Configure L3 Interface
  nxos_config:
    lines:
    - description {{ description }}
    - vrf member {{ vrf }}
    - ip address {{ network_ip | ipmath(5) }}{{ prefix }} tag {{ vrf }}
    - no shutdown
    parents: interface Vlan{{ vlan_id }}

- name: Configure HSRP
  nxos_hsrp:
    group: "{{ ((vlan_id % 2)*-1)+2 }}"
    vip: "{{ network_ip | ipmath(1) }}"
    priority: '250'
    interface: Vlan{{ vlan_id }}
    preempt: enabled
    version: '2'

#- name: Configure Preempt delay
#  nxos_command:
#    commands:
#    - configure terminal
#    - interface Vlan{{ vlan_id }}
#    - hsrp {{ ((vlan_id % 2)*-1)+2 }}
#    - preempt delay minimum 120
#    - end
#    - copy running-config startup-config

- name: Configure Preempt delay
  nxos_config:
    lines:
    - preempt delay minimum 120
    parents: 
    - interface Vlan{{ vlan_id }}
    - hsrp {{ ((vlan_id % 2)*-1)+2 }}
...
