--- 
- name: Configure L3 Interface
  nxos_config:
    lines:
    - description {{ description }}
    - vrf member {{ vrf }}
    - ip address {{ network_ip | ipmath(5) if inventory_hostname == "R1" else network_ip | ipmath(6) }}{{ prefix }} tag {{ vrf }}
    - no shutdown
    parents: interface Vlan{{ vlan_id }}

- name: Set Facts
  set_fact:
    high = '250'
    low = '200'
    
- name: Configure HSRP
  nxos_hsrp:
    group: "{{ ((vlan_id % 2)*-1)+2 }}"
    vip: "{{ network_ip | ipmath(1) }}"
    priority: {% if "R2" in inventory_hostname %}'250'{% else %}'200'{% endif %}    
    interface: Vlan{{ vlan_id }}
    preempt: enabled
    version: '2'
  when: inventory_hostname == "R2" 
  #when: inventory_hostname == "R2" or inventory_hostname == "R1"

#- name: Configure HSRP
#  nxos_hsrp:
#    group: "{{ ((vlan_id % 2)*-1)+2 }}"
#    vip: "{{ network_ip | ipmath(1) }}"
#    priority: '200' 
#    interface: Vlan{{ vlan_id }}
#    preempt: disabled
#    version: '2'
#  when: inventory_hostname == "R1"

- name: Configure Preempt delay
  nxos_config:
    lines:
    - preempt delay minimum 120
    parents: 
    - interface Vlan{{ vlan_id }}
    - hsrp {{ ((vlan_id % 2)*-1)+2 }}
  when: inventory_hostname == "R2"
...
