---
- ios_static_routes:
    config:
    - address_families:
      - afi: ipv4
        routes:
        - dest: "{{ route }}"
          next_hops:
          - forward_router_address: "{{ route_nh }}"
            name: "{{ route_name }}"
    state: merged
...
